vich_uploader:
    db_driver: orm

    mappings:
        path_images:
            uri_prefix: /upload/images
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
